config/routes.rb
Rails.application.routes.draw do

  root 'frms#index'

  get '/kaydol', to: 'users#new', as: :register
  get '/giris', to: "sessions#new", as: :login
  get '/cikis', to: "sessions#destroy", as: :logout
  resource :session, only: [:new, :create, :destroy]

  get '/forumlar', to: 'frms#index', as: :forums
  get '/forumlar/:id', to: 'frms#show', as: :forum

  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', path_names: {new: 'Yeni'}
  end

  resources :topics, except: [:index, :new, :create], path: 'konular', path_names: {edit: 'duzenle'} do
    resources :comments, only: [:new, :create], path: 'yorumlar', path_names: {new: 'yeni'}
  end

  resources :comments, only: [:edit, :update, :destroy], path: 'yorumlar', path_names: {edit: 'düzenle'}

  get ':id', to: 'users#show', as: :profile
  get ':id/edit', to: 'users#edit', as: :edit_profile
  get '/users/new', redirect('/kaydol')
  resources :users, except: :index


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :body, presence: true
  validates :user, presence: true
  validates :topic, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :validate_user!
  before_action only: [:edit, :update, :destroy] do
    validate_permission!(select_comment.user)
  end

  def new
    @topic = Topic.find(params[:topic_id])
    puts params[:parameters]
    @comment = @topic.comments.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @topic, notice: 'Yorumunuz eklendi'
    else
      render :new
    end

  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment.topic, notice: 'Yorumunuz güncellendi'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to @comment.topic, notice: "Yorumunuz başarıyla silindi"
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  private
  def select_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p><%= comment.body %></p>
  <small class="details">
    <%= link_to comment.user.username, profile_path(comment.user) %> tarafından
    <%= time_ago_in_words comment.created_at %> önce gönderildi.
    <% if current_user == comment.user %>
        <%= link_to 'Düzenle', edit_comment_path(comment) %>
        <%= link_to 'Sil', comment, method: :delete %>
    <% end %>
  </small>
</div>

app/views/comments/_form.html.erb
<% form_params = params[:action] == 'new' ? [@topic,@comment] : @comment %>
<%= form_for form_params do |form| %>
    <% if @comment.errors.any? %>
        <div class="row panel callout radius">
          <p>Aşağıdaki hataları düzeltip tekrar deneyiniz</p>
          <ul class="square">
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <%= form.text_area :body, class: 'comment-area' %>
    <%= form.submit class: 'tiny button radius' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Yorumu düzenle</h1>
<%= render 'form' %>

app/views/comments/new.html.erb
<div class="topics panel columns radius">
  <h2><%= @topic.title %></h2>
  <p><%= @topic.body %></p>
  <small class="details">
    <span class="forum-name">
      <%= link_to @topic.frm.name, forum_path(@topic.frm) %>
    </span>

    <%= link_to @topic.user.username, profile_path(@topic.user) %> tarafından
    <%= time_ago_in_words @topic.created_at %> önce gönderildi
  </small>
</div>

<div class="small-11 columns offset-1">
  <h4>Konuya yorum yapın</h4>
  <%= render 'form' %>
</div>