config/routes.rb
Rails.application.routes.draw do

  root 'frms#index'

  get '/kaydol', to: 'users#new', as: :register
  get '/giris', to: "sessions#new", as: :login
  get '/cikis', to: "sessions#destroy", as: :logout
  resource :session, only: [:new, :create, :destroy]

  get '/forumlar', to: 'frms#index', as: :forums
  get '/forumlar/:id', to: 'frms#show', as: :forum

  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', path_names: {new: 'Yeni'}
  end

  resources :topics, except: [:index, :new, :create], path: 'konular', path_names: {edit: 'duzenle'} do
    resources :comments, only: [:new, :create], path: 'yorumlar', path_names: {new: 'yeni'}
  end

  resources :comments, only: [:edit, :update, :destroy], path: 'yorumlar', path_names: {edit: 'düzenle'}

  get ':id', to: 'users#show', as: :profile
  get ':id/edit', to: 'users#edit', as: :edit_profile
  get '/users/new', redirect('/kaydol')
  resources :users, except: :index


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :frm
  has_many :comments,dependent: :destroy

  validates :user, presence: true
  validates :frm, presence: true #hem nesne varlığı hem de alttaki :forum_id varlığı kontrol edilmelidir yoksa saçma bir kayıt kabul edilebilir.

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 20}
  validates :user_id, presence: true
  validates :frm_id, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  #before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :validate_user!, except: [:show]
  before_action only: [:edit, :update, :destroy] do
    validate_permission!(set_topic.user)
  end
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
  end

  # GET /topics/new
  def new
    @forum = Frm.find(params[:forum_id])
    @topic = @forum.topics.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @forum = Frm.find(params[:forum_id])
    @topic = @forum.topics.new(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to @topic, notice: "Konu başarıyla oluşturuldu"
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    redirect_to root_url,notice: "konu başarıyla silindi"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:forum_id, :title, :body)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="large-12 medium-12 medium-centered columns">
  <% form_url = params[:action] == 'new' ? forum_topics_path : @topic %>
  <%= form_for @topic, url: form_url do |f| %>
      <% if @topic.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

            <ul>
              <% @topic.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<div class="topic columns">
  <div class="small-10 columns">
    <h5><%= link_to topic.title, topic %></h5>
    <p><%= truncate topic.body, length: 50 %></p>
    <small class="details">
      <%= link_to topic.user.username, profile_path(topic.user) %> tarafından
      <%= time_ago_in_words topic.created_at %> önce gönderildi
    </small>
  </div>
  <div class="small-2 columns text-center answer-count">
    <strong><%= topic.comments.count %></strong><br>Yanıt
  </div>
  <small class="details">
    <% unless params[:action] == 'show' && params[:controller] == 'frms' %>
    <span class="forum-name">
      <%= link_to topic.frm.name, forum_path(topic.frm) %>
    </span>
    <% end %>
  </small>
</div>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', forum_topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="topics panel columns radius">
  <h2><%= @topic.title %></h2>
  <p><%= @topic.body %></p>
  <small class="details">
    <span class="forum-name">
      <%= link_to @topic.frm.name, forum_path(@topic.frm) %>
    </span>
    <%= link_to_unless_current @topic.user.username, profile_path(@topic.user) %> Tarafından
    <%= time_ago_in_words @topic.created_at %> önce gönderildi
  </small>
</div>
<div>
  <%= link_to "Yorum Ekle", new_topic_comment_path(@topic), class: 'tiny button radius' if signed_in? %>
  <% if current_user == @topic.user %>
      <%= link_to "Düzenle", edit_topic_path(@topic), class: 'tiny button radius' %>
      <%= link_to "Sil", @topic, method: :delete, class: 'tiny button alert radius', data: {confirm: 'Emin misin'} %>
  <% end %>
</div>

<div class="comments">
  <h2>Yorumlar (<%= @topic.comments.count %>)</h2>
  <%= render @topic.comments #_comment.html.erb render eder
  %>
</div>