config/routes.rb
Rails.application.routes.draw do

  root 'frms#index'

  get '/kaydol', to: 'users#new', as: :register
  get '/giris', to: "sessions#new", as: :login
  get '/cikis', to: "sessions#destroy", as: :logout
  resource :session, only: [:new, :create, :destroy]

  get '/forumlar', to: 'frms#index', as: :forums
  get '/forumlar/:id', to: 'frms#show', as: :forum

  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', path_names: {new: 'Yeni'}
  end

  resources :topics, except: [:index, :new, :create], path: 'konular', path_names: {edit: 'duzenle'} do
    resources :comments, only: [:new, :create], path: 'yorumlar', path_names: {new: 'yeni'}
  end

  resources :comments, only: [:edit, :update, :destroy], path: 'yorumlar', path_names: {edit: 'düzenle'}

  get ':id', to: 'users#show', as: :profile
  get ':id/edit', to: 'users#edit', as: :edit_profile
  get '/users/new', redirect('/kaydol')
  resources :users, except: :index


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/frm.rb
class Frm < ApplicationRecord
  has_many :topics
  has_many :comments, through: :topics

  validates :name, presence: true, uniqueness: true
end

app/controllers/frms_controller.rb
class FrmsController < ApplicationController
  def index
    @frms = Frm.all
    @topics = Topic.all
  end

  def show
    @frms = Frm.all
    @forum = Frm.find(params[:id])
  end
end

app/helpers/frms_helper.rb
module FrmsHelper
end

app/views/frms/_forums.html.erb
<li><%= link_to forum.name, forum_path(forum) %></li>

app/views/frms/index.html.erb
<% content_for(:forum_content) do %>
    <div class="large-12 columns">
      <h1>Hoş geldiniz</h1>
      <div class="topics panel columns radius">
        <% if @topics.any? %>
            <%= render @topics %>
        <% else %>
        <p>Henüz Hiç bir konu açılmamış</p>
        <% end %>
      </div>
    </div>
<% end %>

app/views/frms/show.html.erb
<% content_for(:forum_content) do %>
    <div class="large-12 columns">
      <h1><%= @forum.name %> forumu</h1>
      <p>Foruma ait konular</p>
      <%= link_to 'Konu Aç', new_forum_topic_path(@forum), class: 'tiny button right' %>
    </div>
    <div class="topics panel columns radius">
      <% if @forum.topics.any? %>
          <%= render @forum.topics %>
      <% else %>
          <p>Henüz hiç konu açılmamış</p>
      <% end %>
    </div>
<% end %>