config/routes.rb
Rails.application.routes.draw do

  root 'frms#index'

  get '/kaydol', to: 'users#new', as: :register
  get '/giris', to: "sessions#new", as: :login
  get '/cikis', to: "sessions#destroy", as: :logout
  resource :session, only: [:new, :create, :destroy]

  get '/forumlar', to: 'frms#index', as: :forums
  get '/forumlar/:id', to: 'frms#show', as: :forum

  resources :forums, only: [:index, :show], path: 'forumlar' do
    resources :topics, only: [:new, :create], path: 'konular', path_names: {new: 'Yeni'}
  end

  resources :topics, except: [:index, :new, :create], path: 'konular', path_names: {edit: 'duzenle'} do
    resources :comments, only: [:new, :create], path: 'yorumlar', path_names: {new: 'yeni'}
  end

  resources :comments, only: [:edit, :update, :destroy], path: 'yorumlar', path_names: {edit: 'düzenle'}

  get ':id', to: 'users#show', as: :profile
  get ':id/edit', to: 'users#edit', as: :edit_profile
  get '/users/new', redirect('/kaydol')
  resources :users, except: :index


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div data-alert class="alert-box <% flash_class(type) %>">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
<% end %>

app/views/layouts/_top_bar.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Rails Forumu</a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <% if signed_in? %>
            <%= current_user.username %>
            <ul class="dropdown">
              <li><%= link_to "Profilimi Görüntüle", profile_path(current_user) %></li>
              <li><%= link_to "Çıkış", logout_path %></li>
            </ul>
        <% else %>
            <li class="divider"></li>
            <li><%= link_to 'Kaydol', register_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Oturum Aç', login_path %></li>
            <li class="divider"></li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render "layouts/top_bar" %>
<div class="row">
  <div class="row">
    <%= render "layouts/flash_messages" %>
  </div>
  <%= content_for?(:content) ? yield(:content) : yield %>
</div>

</body>
</html>

app/views/layouts/frms.html.erb
<% content_for(:content) do %>
    <div class="large-3 columns panel">
      <h3>Forumlar</h3>
      <ul class="side-nav">
        <% @frms.each do |forum| %>
            <li><%= link_to forum.name, forum_path(forum) %></li>
        <% end %>
      </ul>
    </div>

    <div class="large-9 columns">
      <%= yield :forum_content %>
    </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/profile.html.erb
<% content_for(:content) do %>
    <div class="row">
      <div class="large-12 columns">
        <div class="large-2 columns">
          <!--<img src="http://placehold.it/160x160" class="profile-image" alt=""/> -->
          <%= image_tag @user.avatar_url, class: 'profile-image' %>
        </div>

        <div class="large-10 columns">
          <h2><%= @user.name %></h2>
          <p><%= @user.email %></p>
          <div class="button-bar">
            <ul class="button-group radius">
              <li><%= link_to "Konular", user_path(@user, sayfa: 'konular'), class: 'small button secondary' %></li>
              <li><%= link_to "Yorumlar", user_path(@user, sayfa: 'yorumlar'), class: 'small button secondary' %></li>
              <% if @user == current_user %>
                  <li><%= link_to "Profilimi Düzenle", edit_user_path(@user), class: 'small button secondary' %></li>
                  <li><%= link_to "Hesabımı Sil", @user, data: {confirm: "Hesabınızı silmek istediğinizden emin misiniz?"}, class: 'small button alert', method: :delete %></li>
              <% end %>
            </ul>
          </div>
          <div class="large-12 columns">
            <%= yield(:profile_content) %>
          </div>
        </div>
      </div>
    </div>
<% end %>
<%= render template: 'layouts/application' %>